apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: <SECRET_NAME>
  namespace: default
spec:
  template:
    type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: <PATH_IN_SECRET_BACKEND>
        property: username
    - secretKey: password
      remoteRef:
        key: <PATH_IN_SECRET_BACKEND>
        property: token
  refreshInterval: 1h
