apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: <SECRET_NAME>
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: Opaque
  data:
    - secretKey: <KEY_INSIDE_K8S_SECRET>
      remoteRef:
        key: <PATH_IN_SECRET_BACKEND>
        property: <FIELD_INSIDE_SECRET>
