apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: <COMPONENT_NAME>
  namespace: default
spec:
  owner:
    projectName: default
  componentType:
    kind: ClusterComponentType
    name: deployment/service
  autoDeploy: true
  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: https://github.com/<ORG>/<REPO>
        revision:
          branch: main
        appPath: /<PATH_TO_APP>
      docker:
        context: /<PATH_TO_APP>
        filePath: /<PATH_TO_APP>/Dockerfile
